// CRC-64 checksum matching Valkey/Redis RDB format.
//
// Parameters (from valkey/src/crc64.c, generated by pycrc):
//   Width     = 64
//   Poly      = 0xad93d23594c935a9
//   ReflectIn = true
//   ReflectOut= true
//   XorOut    = 0x0000000000000000
//
// The reflected (bit-reversed) polynomial is used for the LSB-first table
// implementation. This matches CRC64_REVERSED_POLY in valkey/src/crcspeed.c.
// Init value is 0 (rio.cksum starts at 0 in rioFileIO).

const POLY: u64 = 0x95ac9329ac4bc9b5;

/// Precomputed CRC-64 lookup table (256 entries).
const fn make_table() -> [u64; 256] {
    let mut table = [0u64; 256];
    let mut i: u32 = 0;
    while i < 256 {
        let mut crc = 0u64;
        let mut j = 0;
        while j < 8 {
            // ReflectIn: process LSB first
            if ((i >> j) ^ (crc as u32)) & 1 == 1 {
                crc = (crc >> 1) ^ POLY;
            } else {
                crc >>= 1;
            }
            j += 1;
        }
        table[i as usize] = crc;
        i += 1;
    }
    table
}

static TABLE: [u64; 256] = make_table();

/// Compute CRC-64 over a byte slice, starting from `crc` (use 0 for initial).
pub fn crc64(mut crc: u64, data: &[u8]) -> u64 {
    for &byte in data {
        let idx = ((crc ^ byte as u64) & 0xFF) as usize;
        crc = TABLE[idx] ^ (crc >> 8);
    }
    crc
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_crc64_empty() {
        assert_eq!(crc64(0, b""), 0);
    }

    #[test]
    fn test_crc64_composable() {
        let a = crc64(0, b"12345");
        let b = crc64(a, b"6789");
        let full = crc64(0, b"123456789");
        assert_eq!(b, full, "CRC-64 should be composable");
        assert_ne!(full, 0, "CRC-64 of non-empty data should be non-zero");
    }

    #[test]
    fn test_crc64_golden_value() {
        // Golden value extracted from tests/fixtures/empty.rdb (Valkey 9.0).
        // The stored CRC covers all 87 bytes from the header through the EOF opcode.
        let data = std::fs::read("../../tests/fixtures/empty.rdb").unwrap();
        let payload = &data[..data.len() - 8]; // everything except 8-byte CRC trailer
        let stored_crc = u64::from_le_bytes(data[data.len() - 8..].try_into().unwrap());
        let computed = crc64(0, payload);
        assert_eq!(
            computed, stored_crc,
            "CRC-64 mismatch: computed 0x{:016x}, stored 0x{:016x}",
            computed, stored_crc
        );
    }
}
